---
swagger: "2.0"
info:
  title: Fuse-Useralert-API
  version: 1.0.0
host: 0.0.0.0
basePath: /cicd
schemes:
- http
paths:
  /maingateway/profile/{acctid}:
    get:
      tags:
      - maingateway
      operationId: route1
      parameters:
      - name: acctid
        in: path
        description: user profile id
        required: true
        type: string
      responses:
        200:
          description: data recived
securityDefinitions:
  apikey:
    type: apiKey
    description: Use a 3scale API Key
    name: api-key
    in: header
security:
- apikey: []
tags:
- name: sourcegateway
  description: API Gateway
